### ISSUE TITLE
Add Google Analytics to operationspark.org

### ISSUE THREAD

**Issue by ptbarnum4** [OperationSpark/operationspark-org-website-2022#173]
> Originally created by @maxgaudin https://github.com/OperationSpark/greenlight-v2/issues/1603

## Is your feature request related to a problem? Please describe.
Please add Google Analytics to the website. Here is the info:

Below is the Google tag for this account. Copy and paste it in the code of every page of your website, immediately after the <head> element. Don’t add more than one Google tag to each page.

```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-02XDMYQXV1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-02XDMYQXV1');
</script>
```

**Comment by maxgaudin** [comment]
@ptbarnum4 can you let me know when you think we can get this added? we're going to start running ads this week
