### ISSUE TITLE
[GMAIL] Op Spark email filtered into the "Promotions" Tab to the Inbox

### ISSUE THREAD

**Issue by DennisPintilie** [OperationSpark/operationspark-org-website-2022#44]
**Describe the bug**
After the student signup form is completed and submitted, the email from OS is hidden in the promotions tab while the Zoom email is in my inbox tab.

**To Reproduce**
1. Go to Free Info Session
2. Fill out form and submit
3. Go to your email and check the Promotions Tab
4. See email from OS

**Expected behavior**
I have expected for the OS email to be sent in my Inbox tab not Promotions tab.

**Screenshots**
 - N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version 1.45

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
No additional context

**Comment by ptbarnum4** [comment]
Unfortunately, this is out of our control
