### ISSUE TITLE
Blocker on signup for info session form

### ISSUE THREAD

**Issue by Santolococo** [OperationSpark/operationspark-org-website-2022#46]
**Describe the bug**
we can get to the info session signup form and we can fill all of the boxes however if you select the "none of these fit my schedule" option and hit submit you will get an error message and not be able to complete the form. 

**To Reproduce**
1. Go to 'Free info session @ operationspark.org'
2. Click on 'select an info session date'
3. Scroll down to 'none of these fit my schedule'
4. See error on submit that 

**Expected behavior**
I expect the registeration page to allow me to select any option available. If there is a None of these fit my schedule option, I should be able to click this option and complete the form still. 

**Screenshots**
![image](https://user-images.githubusercontent.com/75284767/204908205-f5fa2139-8f30-4e01-b8ca-dd717f8d7347.png)
![image](https://user-images.githubusercontent.com/75284767/204908252-2535232a-480e-48cb-907c-27b8ae99b030.png)
![image](https://user-images.githubusercontent.com/75284767/204908323-633a5e3e-f650-461e-9916-63a633e1950a.png)
![image](https://user-images.githubusercontent.com/75284767/204908378-9d31f5bc-39b2-45b5-8e59-791441426ab3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: N/a
 - OS: n/a
 - Browser: n/a
 - Version: n/a 

**Additional context**

**Comment by harveysanders** [comment]
Possibly resolved by https://github.com/OperationSpark/service-signups/pull/33
