### ISSUE TITLE
Email and SMS not sending on signup form

### ISSUE THREAD

**Issue by Wyndelle** [OperationSpark/operationspark-org-website-2022#47]
On 11/21 and 11/30 I submitted a signup form under the two emails `redacted` and the two phone numbers `redacted`. I didn't receive an email; SMS and the log isn't showing an attempt either time. 

Steps to reproduce the behavior hasn't been clear. 
However, when this occurred, I did the following:
1. Go to 'https://testing.operationspark.org/'
2. Click on 'Free Info Session'
3. Complete form with valid email and phone number
4. Select Info date of 'Monday, December 5th, 1:00pm'
5. Submit Register
6. Observe Success popup

The process of filling out the form gives no reason to suspect an error, however I never received an email or SMS in any inbox.

Failed Email conditions:
 - OS: Windows
 - Browser: chrome & Microsoft edge
 - Version: 11
 - Email carrier:  Gmail

Failed SMS conditions: 
 - Device: Samsung Ao3
 - OS: android 
 - Text manager: Messages+
 - Text manager: Textfree

For additional context, I received this error afterwards I reset my computer (it was not shut down for 23 days) and cleared my browsers (Microsoft edge) cache and refilled the form. After this I received both the sms and email.

**Comment by harveysanders** [comment]
So far we have not been able to reproduce this issue. We'll keep it open for a bit and keep a look out.

**Comment by ptbarnum4** [comment]
Cannot reproduce. Feel free to reopen if this happens again
