### ISSUE TITLE
Update HighSchool Application Fall 2023

### ISSUE THREAD

**Issue by harveysanders** [OperationSpark/operationspark-org-website-2022#96]
@mraychaudhuri  would like to restore the High School application.
- [ ] Update copy
- [ ] Update Schedule
  - Use Fall 2022 Schedule as a starting point
  
See this PR?
https://github.com/OperationSpark/operationspark-org-website-2022/pull/20

**Comment by mraychaudhuri** [comment]
@harveysanders here are the updates with some notes:

https://docs.google.com/document/d/1OHUdwRhbMz4jmEk6Ox6bMKZ92nAg66psXaeTNfgYLzA/edit?usp=sharing
